version: '3'

services:
  flask:
      container_name: flask
      image: "flask:test"
      ports:
      - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      ports:
      - "80:80"
      networks:
      - backend
  
  # mongodb:
  #     container_name: mongodb
  #     image: "mongodb:test"
  #     ports:
  #     -  "27017:27017"
  #     networks:
  #     -  backend

networks:
  backend:
    driver: bridge