version: '3'

services:
  server:
      container_name: server
      image: "server:test"
      ports:
      - "5000:5000"
      networks:
      - backend
  chatbot:
      container_name: chatbot
      image: "chatbot:test"
      ports:
      - "5555:5555"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      ports:
      - "80:80"
      networks:
      - backend
  mongodb:
      container_name: mongodb
      image: "mongodb:test"
      ports:
      -  "27017:27017"
      networks:
      -  backend

networks:
  backend:
    driver: bridge