FROM nginx:1.17.4
LABEL email="hello2273@naver.com"
LABEL name="Dogyu Hwang"
LABEL description="My Weather App NginX"

COPY default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]