FROM centos:latest
LABEL email="hello2273@naver.com"
LABEL name="Dogyu Hwang"
LABEL description="My Weather App NginX"

RUN yum install -y epel-release
RUN yum install -y nginx

# COPY ./ /home/ec2-user/docker/nginx
COPY ./nginx.conf /etc/nginx                                                                       
                                                                       
EXPOSE 80                                                                       
CMD ["nginx","-g","daemon off;"]