FROM python:3.7
LABEL email="hello2273@naver.com"
LABEL name="Dogyu Hwang"
LABEL description="My Weather App Chatbot"

ADD . /app
WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["run2.py"]